/* eslint-disable react/no-unescaped-entities */
import { Box } from "@mui/material";
import { Stack } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import TodoAddBar from "../components/TodoAddBar";
import TodoList from "../components/TodoList";
import store from "../redux/store";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	console.log(store.getState());
	const unsubscribe = store.subscribe(() =>
		console.log("State after dispatch: ", store.getState())
	);
	store.dispatch({ type: "todos/todoAdded", payload: "Learn about actions" });
	store.dispatch({ type: "todos/todoAdded", payload: "Learn about reducers" });
	store.dispatch({ type: "todos/todoAdded", payload: "Learn about stores" });

	store.dispatch({ type: "todos/todoToggled", payload: 0 });
	store.dispatch({ type: "todos/todoToggled", payload: 1 });
	unsubscribe();
	return (
		<div className={styles.container}>
			<Head>
				<title>Mint's Todo App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box sx={{ padding: 5 }}>
				<Stack justifyContent="center" alignItems="center" spacing={2}>
					<TodoAddBar />
					<TodoList />
				</Stack>
			</Box>
		</div>
	);
};

export default Home;
