/* eslint-disable react/no-unescaped-entities */
import { Stack } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import LoadingScreen, { RootStyle } from "../components/LoadingScreen";
import TodoAddBar from "../components/TodoAddBar";
import TodoList from "../components/TodoList";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { Box, Typography } from "@mui/material";

const Home: NextPage = () => {
	const [visible, setVisible] = useState(true);

	useEffect(() => {
		setTimeout(() => {
			setVisible(false);
		}, 5000);
	});
	return (
		<div className={styles.container}>
			<Head>
				<title>Mint's Todo App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				{visible && <LoadingScreen />}

				<Box
					sx={{
						width: "100%",
						height: "100%",
						position: "fixed",
						display: "flexed",
						alignItems: "center",
						justifyContent: "center",
						backgroundColor: "mintcream",
					}}>
					<Stack spacing={2}>
						<motion.div
							initial={{ y: 10, opacity: 0 }}
							animate={{ y: 0, opacity: 1 }}
							exit={{ y: -10, opacity: 0 }}
							transition={{ duration: 1.2 }}>
							<TodoAddBar />
						</motion.div>
						<motion.div
							initial={{ y: 10, opacity: 0 }}
							animate={{ y: 0, opacity: 1 }}
							exit={{ y: -10, opacity: 0 }}
							transition={{ duration: 1.2 }}>
							<TodoList />
						</motion.div>
					</Stack>
				</Box>
			</main>
		</div>
	);
};

export default Home;
